#!/bin/bash
set -e -u -o pipefail

#Variables
DAEMON=sockd

gpid=$(pgrep ${DAEMON})
if [[ -f /run/${DAEMON}.pid ]]; then
    rpid=$(cat /run/${DAEMON}.pid)
    NOTFOUND=1
    for p in ${gpid}; do
        if [ ${p} -eq ${rpid} ]; then
            NOTFOUND=0
            break
        fi
    done
    if [[ 1 -eq ${NOTFOUND} ]]; then exit 1; fi
fi

if [[ -z ${gpid} ]]; then
    exit 1
fi
