#!/bin/bash
set -e -u -o pipefail

#Variables
. /etc/service/date.sh --source-only
[[ -f /etc/service/utils.sh ]] && source /etc/service/utils.sh || true

log "########################################################"
log "INFO: dante: stopping"
[[ -f /run/sockd.pid ]] && kill $(cat /run/sockd.pid)
sleep 1
for p in $(pgrep sockd); do kill -9 $p; done
