#!/bin/bash
set -e -u -o pipefail

#Variables

[[ -f /etc/service/utils.sh ]] && source /etc/service/utils.sh || true

SOURCE_DANTE_CONF=/baseconfig/dante.conf
DANTE_CONF=/config/dante.conf
dante_d=''
DEBUG=${DEBUG:-0}
DANTE_DEBUG=${DEBUG:-0}
DANTE_LOGLEVEL=${DANTE_LOGLEVEL:-"error"}
DANTE_ERRORLOG=${DANTE_DANTE_ERRORLOG:-"/dev/null"}
[[ ${DEBUG:-0} -eq 1 ]] && set -x && dante_d=" -d9" && DANTE_DEBUG=9 && DANTE_LOGLEVEL=${DANTE_LOGLEVEL-"connect disconnect error data"}
DANTE_LOGLEVEL=${DANTE_LOGLEVEL//\"/}
DANTE_ERRORLOG=${DANTE_ERRORLOG//\"/}

export INTERFACE=$(ip addr show eth0 | grep -oE 'inet [^/]+' | cut -f2 -d' ')
sed "s/INTERFACE/${INTERFACE}/" ${SOURCE_DANTE_CONF} >${DANTE_CONF}
sed -i "s/DEBUG/${DANTE_DEBUG}/" ${DANTE_CONF}
sed -i "s/DANTE_LOGLEVEL/${DANTE_LOGLEVEL}/" ${DANTE_CONF}

#basic Auth
TCREDS_SECRET_FILE=/run/secrets/TINY_CREDS
if [[ -f ${TCREDS_SECRET_FILE} ]]; then
    TINYUSER=$(head -1 ${TCREDS_SECRET_FILE})
    TINYPASS=$(tail -1 ${TCREDS_SECRET_FILE})
fi
if [[ -n ${TINYUSER:-''} ]] && [[ -n ${TINYPASS:-''} ]]; then
    createUserForAuthifNeeded ${TINYUSER}
    echo ${TINYUSER}:${TINYPASS} | chpasswd
    sed -i -r "s/#?socksmethod: .*/socksmethod: username/" ${DANTE_CONF}
else
    sed -i -r "s/socksmethod: .*/socksmethod: none/" ${DANTE_CONF}
fi

[[ -n ${DANTE_LOGLEVEL} ]] && sed -i "s/log: DANTE_LOGLEVEL/log: ${DANTE_LOGLEVEL}/" ${DANTE_CONF}
[[ -n ${DANTE_ERRORLOG} ]] && sed -i "s#errorlog: /dev/null#errorlog: ${DANTE_ERRORLOG}#" ${DANTE_CONF}

log "INFO:" "########################################################"
log "INFO: DANTE: Waiting for tun0 to be up"
while [[ $(ifconfig tun0 2>&1 | grep -c "00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00") -eq 0 ]]; do
    sleep 10
done

log "INFO: DANTE: check configuration socks proxy"
sockd -Vf ${DANTE_CONF}
log "INFO: DANTE: set configuration socks proxy"
if [[ 0 -le $(ps -ef | grep -c sockd) ]]; then
    sockd -N 2 -f ${DANTE_CONF}
else
    pkill -9 sockd
    sockd -N 2 -f ${DANTE_CONF}
fi

sleep 5
