#!/bin/bash
set -e -u -o pipefail

#Variables

[[ -f /etc/service/utils.sh ]] && source /etc/service/utils.sh || true

log "########################################################"
log "INFO: unbound: stopping"
[[ -f /run/unbound.pid ]] && kill $(cat /run/unbound.pid)
sleep 1
for p in $(pgrep unbound); do kill -9 $p; done