#!/bin/bash
set -e -u -o pipefail

#Variables
[[ -f /etc/service/utils.sh ]] && source /etc/service/utils.sh || true
DAEMON=unbound

log "INFO:" "########################################################"
log "INFO: ${DAEMON}: stopping"
[[ -f /run/${DAEMON}.pid ]] && kill $(cat /run/${DAEMON}.pid) && rm -f /run/${DAEMON}.pid || true
sleep 1
for p in $(pgrep ${DAEMON}); do kill $p; done
sleep 2
for p in $(pgrep ${DAEMON}); do kill -9 $p; done
log "INFO: ${DAEMON}: stopped"