#!/usr/bin/env bash
set -e -u -o pipefail

#Variables
[[ -f /etc/service/utils.sh ]] && source /etc/service/utils.sh || true

SOURCE_CONF=/baseconfig/unbound.conf
CONF=/config/unbound.conf
DNS=${DNS:-1.1.1.1@853#cloudflare-dns.com 1.0.0.1@853#cloudflare-dns.com}
RESOLV=/etc/resolv.conf

#Main
log "INFO: UNBOUND: set configuration dns unbound"
[[ ! -f /etc/unbound/root.hints ]] && curl -s https://www.internic.net/domain/named.cache -o /etc/unbound/root.hints || true
cp -f ${SOURCE_CONF} ${CONF}
for ip in ${DNS}; do
    echo "  forward-addr: $ip" >>${CONF}
done
echo "    forward-ssl-upstream: yes" >>${CONF}

if [[ 0 -eq $(grep -c "nameserver 127.0.0.1$" /etc/resolv.conf) ]]; then
    log "INFO: UNBOUND : copy original resolv conf"
    cp ${RESOLV} ${RESOLV}.ori
    echo "nameserver 127.0.0.1" >${RESOLV}
fi

log "INFO: UNBOUND : check unbound conf"
unbound-checkconf /config/unbound.conf
log "INFO: UNBOUND : start unbound"
/usr/sbin/unbound -dv -c ${CONF}

log "INFO: UNBOUND: end unbound"
log "INFO: UNBOUND : restoring dns resolution conf"
[[ -f ${RESOLV}.ori ]] && cp ${RESOLV}.ori ${RESOLV}
while true; do
    sleep 30
done
