#!/bin/bash
set -e -u -o pipefail
. /etc/service/date.sh --source-only

cronfile='/var/spool/cron/crontabs/root'

log "CROND: INFO: Removing current cronfile"
rm -f "$cronfile"
log "CROND: INFO: Creating new cronfile"
touch "$cronfile"

#Add cron for GET_OVPN_FILES
#printf "$CRON_OVPN_FILES '/etc/service/openvpn/get-ovpn-files.sh'\n" > "$cronfile"
echo "*/5 * * * * /etc/service/openvpn/healthcheck.sh" >>"$cronfile"
echo "*/1 * * * * /etc/service/openvpn/resolvcheck.sh" >>"$cronfile"

if [[ "${CRON}" ]]; then
  log "INFO: CRON: Your cron settings (${CRON}) will be applied!"
  printf "$CRON '/etc/service/openvpn/get-status-server.sh'\n" >>"$cronfile"
  #Add empty line at the end of file
  sed -i -e '$a\' $cronfile
else
  log "CROND: WARNING: No cron config, server load will not be checked! This is optional!"
  exit 1
fi

crond -f -S -L /dev/fd/1
