#!/bin/bash
set -e -u -o pipefail

#Variables
[[ -f /etc/service/utils.sh ]] && source /etc/service/utils.sh || true
SOCKET="unix-connect:/run/openvpn.sock"
DAEMON=openvpn

log "########################################################"
log "INFO: openvpn: stopping"
[[ -S /run/openvpn.sock ]] && (echo "signal SIGHUP";sleep 1)| socat -s - ${SOCKET} && rm -f /run/openvpn.sock
[[ -f /run/${DAEMON}.pid ]] && kill $(cat /run/${DAEMON}.pid) && rm -f /run/${DAEMON}.pid || true
for p in $(pgrep ${DAEMON}); do kill $p; done
sleep 2
for p in $(pgrep ${DAEMON}); do kill -9 $p; done
route add default dev eth0
echo "nameserver 127.0.0.1" >/etc/resolv.conf
log "INFO: ${DAEMON}: stopped"
