#!/usr/bin/env bash
set -e -u -o pipefail

#Variables

[[ -f /etc/service/utils.sh ]] && source /etc/service/utils.sh || true

SOURCE_CONF=/config/tinyproxy.conf
CONF=/etc/tinyproxy/tinyproxy.conf
TINYPORT=${TINYPORT:-8888}
#Critical (least verbose), Error, Warning, Notice, Connect (to log connections without Info's noise), Info
TINY_LOGLEVEL=${TINY_LOGLEVEL:-Error}
EXT_IP=$(ip addr show tun0 | grep -oE 'inet [^/]+' | cut -f2 -d' ')
INT_IP=$(ip addr show eth0 | grep -oE 'inet [^/]+' | cut -f2 -d' ')
INT_CIDR=$(ip -j a show eth0 | jq  -r '.[].addr_info[0]|"\( .local)/\(.prefixlen)"')

#Main
log "INFO: TINYPROXY: set configuration INT_IP: ${INT_IP}/ EXT_IP: ${EXT_IP} / log level: ${TINY_LOGLEVEL} / local network: ${LOCAL_NETWORK}"
sed "s/TINYPORT/${TINYPORT}/" ${SOURCE_CONF} > ${CONF}
sed -i "s/TINY_LOGLEVEL/${TINY_LOGLEVEL}/" ${CONF}
sed -i "s/#Listen .*/Listen ${INT_IP}/" ${CONF}

sed -i "s!#Allow INT_CIDR!Allow ${INT_CIDR}!" ${CONF}

#Allow only local network or all private address ranges
if [[ -n ${LOCAL_NETWORK} ]];then
    sed -i "s!#Allow LOCAL_NETWORK!Allow ${LOCAL_NETWORK}!" ${CONF}
else
    sed -i "s!#Allow 10!Allow 10!" ${CONF}
    sed -i "s!#Allow 172!Allow 172!" ${CONF}
    sed -i "s!#Allow 192!Allow 192!" ${CONF}
fi

[[ 1 -eq ${DEBUG} ]] && grep -vE "(^#|^$)" ${CONF} || true

log "INFO: TINYPROXY: starting"
/usr/bin/tinyproxy -d -c ${CONF}