#!/usr/bin/env bash
set -e -u -o pipefail

[[ ${DEBUG:-0} -eq 1 ]] && set -x
#Variables
SOURCE_CONF=/config/tinyproxy.conf
CONF=/etc/tinyproxy/tinyproxy.conf
TINYPORT=${TINYPORT:-8888}

#Main
. /etc/service/date.sh --source-only

log "INFO: TINYPROXY: set configuration "

eval "echo \"$(cat ${SOURCE_CONF})\"" > ${CONF}
#Allow only local network or all private address ranges
if [[ -n ${LOCAL_NETWORK} ]];then
    sed -i "s!#Allow LOCAL_NETWORK!Allow ${LOCAL_NETWORK}!" ${CONF}
else
    sed -i "s!#Allow 10!Allow 10!" ${CONF}
    sed -i "s!#Allow 172!Allow 172!" ${CONF}
    sed -i "s!#Allow 192!Allow 192!" ${CONF}
fi

[[ 1 -eq ${DEBUG} ]] && grep -vE "(^#|^$)" ${CONF} || true

log "INFO: TINYPROXY: starting"
/usr/bin/tinyproxy -d -c ${CONF}
